open:
  api:
    title: "API Challenge-5-meu documentation"
    version: "v2.6.0"
    description: "API Challenge-5-meu"
    license:
      name: "Api license"
      url: "https://github.com/challenge3/challenge-5-meu"

    servers:
        url:
          api: "http://localhost:8080/api"
        description: "server challenge 5 meu"


springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
