
spring:
  config:
    import:
      - classpath:openApi.yaml
      - classpath:security.yaml

  application:
    name: app

  datasource:
    url: jdbc:mysql://localhost:3306/challenge3meu
    username: challenge3meu
    password: 123123

  jpa:
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    servlet:
      path: /api

