
spring:
  config:
    import:
      - classpath:openApi.yaml
      - classpath:security.yaml

  application:
    name: app

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/challenge3meu
    username: challenge3meu
    password: 123123

  jpa:
    show-sql: true
    open-in-view: false

  mvc:
    servlet:
      path: /api

